version: '3'

services:
  redis:
    image: redis:4.0.10
    ports:
      - "6379:6379"
  database:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - my_network
    environment:
      - POSTGRES_DB=pg_dev
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
networks:
  my_network:
