default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  timeout: 5000
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: ar_learning_dev

test:
  <<: *default
  database: ar_learning_test

production:
  <<: *default
  database: ar_learning_prod
